In [1]:
import pandas as pd
import numpy as np
from cobra.io import read_sbml_model
from tqdm.auto import tqdm

In [2]:
from os import listdir
from os.path import isfile, join

mypath = '../models/non-ec/agora/'

onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]
print(onlyfiles)

['Bacteroides_uniformis_ATCC_8492.xml', 'Coprococcus_comes_ATCC_27758.xml', 'Fusobacterium_nucleatum_subsp_nucleatum_ATCC_25586.xml', 'Streptococcus_salivarius_DSM_20560.xml', 'Streptococcus_parasanguinis_ATCC_15912.xml', 'Roseburia_intestinalis_L1_82.xml', 'Escherichia_coli_ED1a.xml', 'Bacteroides_thetaiotaomicron_VPI_5482.xml']

In [3]:
db_l = []

for file in tqdm(onlyfiles):
    file = mypath + file
    model = read_sbml_model(file)
    name = model.id
    name = str(name)
    name = name.strip('M_')
    id_n = name
    name = name.replace('_',' ')
    rxns = len(model.reactions)
    mets = len(model.metabolites)
    name_list = name.split(' ')
    genus = name_list[0]
    species = ' '.join(name_list[1::])
    for i in range(1,7):
        sam_n = i
        sample = f'sample_{sam_n}'
        abundace = np.random.randint(100,500)
        res = [id_n, genus, species, rxns, mets, file, sample, abundace]
        db_l.append(res)
    
db = pd.DataFrame(db_l, columns = ['id','genus','species','reactions','metabolites','file','sample_id','abundace'])
db

  0%|          | 0/8 [00:00<?, ?it/s]

Set parameter Username
Academic license - for non-commercial use only - expires 2024-03-01

,id,genus,species,reactions,metabolites,file,sample_id,abundace
0,Bacteroides_uniformis_ATCC_8492,Bacteroides,uniformis ATCC 8492,2686,2204,../models/non-ec/agora/Bacteroides_uniformis_A...,sample_1,271
1,Bacteroides_uniformis_ATCC_8492,Bacteroides,uniformis ATCC 8492,2686,2204,../models/non-ec/agora/Bacteroides_uniformis_A...,sample_2,399
2,Bacteroides_uniformis_ATCC_8492,Bacteroides,uniformis ATCC 8492,2686,2204,../models/non-ec/agora/Bacteroides_uniformis_A...,sample_3,176
3,Bacteroides_uniformis_ATCC_8492,Bacteroides,uniformis ATCC 8492,2686,2204,../models/non-ec/agora/Bacteroides_uniformis_A...,sample_4,123
4,Bacteroides_uniformis_ATCC_8492,Bacteroides,uniformis ATCC 8492,2686,2204,../models/non-ec/agora/Bacteroides_uniformis_A...,sample_5,322
5,Bacteroides_uniformis_ATCC_8492,Bacteroides,uniformis ATCC 8492,2686,2204,../models/non-ec/agora/Bacteroides_uniformis_A...,sample_6,325
6,Coprococcus_comes_ATCC_27758,Coprococcus,comes ATCC 27758,1034,984,../models/non-ec/agora/Coprococcus_comes_ATCC_...,sample_1,216
7,Coprococcus_comes_ATCC_27758,Coprococcus,comes ATCC 27758,1034,984,../models/non-ec/agora/Coprococcus_comes_ATCC_...,sample_2,490
8,Coprococcus_comes_ATCC_27758,Coprococcus,comes ATCC 27758,1034,984,../models/non-ec/agora/Coprococcus_comes_ATCC_...,sample_3,375
9,Coprococcus_comes_ATCC_27758,Coprococcus,comes ATCC 27758,1034,984,../models/non-ec/agora/Coprococcus_comes_ATCC_...,sample_4,157
10,Coprococcus_comes_ATCC_27758,Coprococcus,comes ATCC 27758,1034,984,../models/non-ec/agora/Coprococcus_comes_ATCC_...,sample_5,454
11,Coprococcus_comes_ATCC_27758,Coprococcus,comes ATCC 27758,1034,984,../models/non-ec/agora/Coprococcus_comes_ATCC_...,sample_6,409
12,Fusobacterium_nucleatum_subsp_nucleatum_ATCC_2...,Fusobacterium,nucleatum subsp nucleatum ATCC 25586,1203,1135,../models/non-ec/agora/Fusobacterium_nucleatum...,sample_1,376
13,Fusobacterium_nucleatum_subsp_nucleatum_ATCC_2...,Fusobacterium,nucleatum subsp nucleatum ATCC 25586,1203,1135,../models/non-ec/agora/Fusobacterium_nucleatum...,sample_2,185
14,Fusobacterium_nucleatum_subsp_nucleatum_ATCC_2...,Fusobacterium,nucleatum subsp nucleatum ATCC 25586,1203,1135,../models/non-ec/agora/Fusobacterium_nucleatum...,sample_3,481
15,Fusobacterium_nucleatum_subsp_nucleatum_ATCC_2...,Fusobacterium,nucleatum subsp nucleatum ATCC 25586,1203,1135,../models/non-ec/agora/Fusobacterium_nucleatum...,sample_4,109
16,Fusobacterium_nucleatum_subsp_nucleatum_ATCC_2...,Fusobacterium,nucleatum subsp nucleatum ATCC 25586,1203,1135,../models/non-ec/agora/Fusobacterium_nucleatum...,sample_5,154
17,Fusobacterium_nucleatum_subsp_nucleatum_ATCC_2...,Fusobacterium,nucleatum subsp nucleatum ATCC 25586,1203,1135,../models/non-ec/agora/Fusobacterium_nucleatum...,sample_6,205
18,Streptococcus_salivarius_DSM_20560,Streptococcus,salivarius DSM 20560,939,852,../models/non-ec/agora/Streptococcus_salivariu...,sample_1,366
19,Streptococcus_salivarius_DSM_20560,Streptococcus,salivarius DSM 20560,939,852,../models/non-ec/agora/Streptococcus_salivariu...,sample_2,384
20,Streptococcus_salivarius_DSM_20560,Streptococcus,salivarius DSM 20560,939,852,../models/non-ec/agora/Streptococcus_salivariu...,sample_3,363
21,Streptococcus_salivarius_DSM_20560,Streptococcus,salivarius DSM 20560,939,852,../models/non-ec/agora/Streptococcus_salivariu...,sample_4,341
22,Streptococcus_salivarius_DSM_20560,Streptococcus,salivarius DSM 20560,939,852,../models/non-ec/agora/Streptococcus_salivariu...,sample_5,456
23,Streptococcus_salivarius_DSM_20560,Streptococcus,salivarius DSM 20560,939,852,../models/non-ec/agora/Streptococcus_salivariu...,sample_6,322
24,Streptococcus_parasanguinis_ATCC_15912,Streptococcus,parasanguinis ATCC 15912,1258,1231,../models/non-ec/agora/Streptococcus_parasangu...,sample_1,149
25,Streptococcus_parasanguinis_ATCC_15912,Streptococcus,parasanguinis ATCC 15912,1258,1231,../models/non-ec/agora/Streptococcus_parasangu...,sample_2,146
26,Streptococcus_parasanguinis_ATCC_15912,Streptococcus,parasanguinis ATCC 15912,1258,1231,../models/non-ec/agora/Streptococcus_parasangu...,sample_3,455
27,Streptococcus_parasanguinis_ATCC_15912,Streptococcus,parasanguinis ATCC 15912,1258,1231,../models/non-ec/agora/Streptococcus_parasangu...,sample_4,240
28,Streptococcus_parasanguinis_ATCC_15912,Streptococcus,parasanguinis ATCC 15912,1258,1231,../models/non-ec/agora/Streptococcus_parasangu...,sample_5,216
29,Streptococcus_parasanguinis_ATCC_15912,Streptococcus,parasanguinis ATCC 15912,1258,1231,../models/non-ec/agora/Streptococcus_parasangu...,sample_6,193
30,Roseburia_intestinalis_L1_82,Roseburia,intestinalis L1 82,1983,1691,../models/non-ec/agora/Roseburia_intestinalis_...,sample_1,471
31,Roseburia_intestinalis_L1_82,Roseburia,intestinalis L1 82,1983,1691,../models/non-ec/agora/Roseburia_intestinalis_...,sample_2,387
32,Roseburia_intestinalis_L1_82,Roseburia,intestinalis L1 82,1983,1691,../models/non-ec/agora/Roseburia_intestinalis_...,sample_3,266
33,Roseburia_intestinalis_L1_82,Roseburia,intestinalis L1 82,1983,1691,../models/non-ec/agora/Roseburia_intestinalis_...,sample_4,141
34,Roseburia_intestinalis_L1_82,Roseburia,intestinalis L1 82,1983,1691,../models/non-ec/agora/Roseburia_intestinalis_...,sample_5,135
35,Roseburia_intestinalis_L1_82,Roseburia,intestinalis L1 82,1983,1691,../models/non-ec/agora/Roseburia_intestinalis_...,sample_6,353
36,Escherichia_coli_ED1a,Escherichia,coli ED1a,3586,3119,../models/non-ec/agora/Escherichia_coli_ED1a.xml,sample_1,436
37,Escherichia_coli_ED1a,Escherichia,coli ED1a,3586,3119,../models/non-ec/agora/Escherichia_coli_ED1a.xml,sample_2,494
38,Escherichia_coli_ED1a,Escherichia,coli ED1a,3586,3119,../models/non-ec/agora/Escherichia_coli_ED1a.xml,sample_3,471
39,Escherichia_coli_ED1a,Escherichia,coli ED1a,3586,3119,../models/non-ec/agora/Escherichia_coli_ED1a.xml,sample_4,211
40,Escherichia_coli_ED1a,Escherichia,coli ED1a,3586,3119,../models/non-ec/agora/Escherichia_coli_ED1a.xml,sample_5,219
41,Escherichia_coli_ED1a,Escherichia,coli ED1a,3586,3119,../models/non-ec/agora/Escherichia_coli_ED1a.xml,sample_6,201
42,Bacteroides_thetaiotaomicron_VPI_5482,Bacteroides,thetaiotaomicron VPI 5482,2438,2041,../models/non-ec/agora/Bacteroides_thetaiotaom...,sample_1,293
43,Bacteroides_thetaiotaomicron_VPI_5482,Bacteroides,thetaiotaomicron VPI 5482,2438,2041,../models/non-ec/agora/Bacteroides_thetaiotaom...,sample_2,231
44,Bacteroides_thetaiotaomicron_VPI_5482,Bacteroides,thetaiotaomicron VPI 5482,2438,2041,../models/non-ec/agora/Bacteroides_thetaiotaom...,sample_3,252
45,Bacteroides_thetaiotaomicron_VPI_5482,Bacteroides,thetaiotaomicron VPI 5482,2438,2041,../models/non-ec/agora/Bacteroides_thetaiotaom...,sample_4,197
46,Bacteroides_thetaiotaomicron_VPI_5482,Bacteroides,thetaiotaomicron VPI 5482,2438,2041,../models/non-ec/agora/Bacteroides_thetaiotaom...,sample_5,194
47,Bacteroides_thetaiotaomicron_VPI_5482,Bacteroides,thetaiotaomicron VPI 5482,2438,2041,../models/non-ec/agora/Bacteroides_thetaiotaom...,sample_6,271

In [4]:
from micom.workflows import build

manifest = build(db, out_folder="../data/micom", model_db=None, cutoff=0.0001, threads=2)

[18:44:38] WARNING  Found existing models for 6 samples. Will skip those. Delete the output folder if   ]8;id=601439;file:///usr/local/Caskroom/miniforge/base/envs/tmcom/lib/python3.9/site-packages/micom/workflows/build.py\build.py]8;;\:]8;id=542437;file:///usr/local/Caskroom/miniforge/base/envs/tmcom/lib/python3.9/site-packages/micom/workflows/build.py#95\95]8;;\
                    you would like me to rebuild them.

Output()

Set parameter Username
Set parameter Username
Academic license - for non-commercial use only - expires 2024-03-01
Academic license - for non-commercial use only - expires 2024-03-01
Read LP format model from file /var/folders/1q/4qg3t0gx0sn39bk35trp5hmm0000gn/T/tmpposhx_h9.lp
Reading time = 0.11 seconds
: 13960 rows, 31643 columns, 117913 nonzeros
Read LP format model from file /var/folders/1q/4qg3t0gx0sn39bk35trp5hmm0000gn/T/tmpaf8dwrwp.lp
Reading time = 0.11 seconds
: 13960 rows, 31643 columns, 117913 nonzeros
Set parameter Username
Set parameter Username
Academic license - for non-commercial use only - expires 2024-03-01
Academic license - for non-commercial use only - expires 2024-03-01
Read LP format model from file /var/folders/1q/4qg3t0gx0sn39bk35trp5hmm0000gn/T/tmpw63f8rsr.lp
Reading time = 0.12 seconds
: 13960 rows, 31643 columns, 117913 nonzeros
Read LP format model from file /var/folders/1q/4qg3t0gx0sn39bk35trp5hmm0000gn/T/tmpn26cc4fq.lp
Reading time = 0.12 seconds
: 13960 rows, 31643 columns, 117913 nonzeros
Set parameter Username
Set parameter Username
Academic license - for non-commercial use only - expires 2024-03-01
Academic license - for non-commercial use only - expires 2024-03-01
Read LP format model from file /var/folders/1q/4qg3t0gx0sn39bk35trp5hmm0000gn/T/tmp187ymev0.lp
Reading time = 0.11 seconds
: 13960 rows, 31643 columns, 117913 nonzeros
Read LP format model from file /var/folders/1q/4qg3t0gx0sn39bk35trp5hmm0000gn/T/tmpjcdeb602.lp
Reading time = 0.11 seconds
: 13960 rows, 31643 columns, 117913 nonzeros

In [5]:
manifest

  sample_id             file
0  sample_1  sample_1.pickle
1  sample_2  sample_2.pickle
2  sample_3  sample_3.pickle
3  sample_4  sample_4.pickle
4  sample_5  sample_5.pickle
5  sample_6  sample_6.pickle

In [6]:
from micom import load_pickle

com1 = load_pickle("../data/micom/sample_1.pickle")
print(len(com1.reactions))

Read LP format model from file /var/folders/1q/4qg3t0gx0sn39bk35trp5hmm0000gn/T/tmp4yoark55.lp
Reading time = 0.12 seconds
: 13960 rows, 31643 columns, 117913 nonzeros
15821

In [7]:
from micom.media import minimal_medium

med = minimal_medium(com1, 0.8)
res_m = []

for k in med.keys():
    print(f'Reaction: {k}, Flux: {med[k]}')
    rx = k
    flux = med[k]
    met = k.strip('EX_')
    res = [k,k,flux,met]
    res_m.append(res)
    
min_med = pd.DataFrame(res_m, columns = ['reaction','reaction','flux','metabolite'])
min_med

Reaction: EX_adn_m, Flux: 0.11583999999955126
Reaction: EX_ca2_m, Flux: 0.002477199999999513
Reaction: EX_cl_m, Flux: 0.002477199999999513
Reaction: EX_cobalt2_m, Flux: 0.0024772000000012895
Reaction: EX_cu2_m, Flux: 0.0024772000000012895
Reaction: EX_fe2_m, Flux: 0.004954400000000803
Reaction: EX_fe3_m, Flux: 0.0024772000000012895
Reaction: EX_gsn_m, Flux: 0.13353080000000261
Reaction: EX_k_m, Flux: 0.0024772000000012895
Reaction: EX_mg2_m, Flux: 0.0024772000000012895
Reaction: EX_mn2_m, Flux: 0.002477199999999513
Reaction: EX_pullulan1200_m, Flux: 0.0063421950979254405
Reaction: EX_pydxn_m, Flux: 0.0024772000000012895
Reaction: EX_zn2_m, Flux: 0.0024772000000012895
Reaction: EX_cgly_m, Flux: 0.06834839999999076
Reaction: EX_metala_m, Flux: 0.10471720000000001
Reaction: EX_pheme_m, Flux: 0.0024772000000012895
Reaction: EX_q8_m, Flux: 0.0024772000000012895
Reaction: EX_nmn_m, Flux: 0.364895799999303
Reaction: EX_man6p_m, Flux: 0.3648957999995872
Reaction: EX_hspg_m, Flux: 1.2385418500001606

             reaction           reaction      flux      metabolite
0            EX_adn_m           EX_adn_m  0.115840           adn_m
1            EX_ca2_m           EX_ca2_m  0.002477           ca2_m
2             EX_cl_m            EX_cl_m  0.002477            cl_m
3        EX_cobalt2_m       EX_cobalt2_m  0.002477       cobalt2_m
4            EX_cu2_m           EX_cu2_m  0.002477           cu2_m
5            EX_fe2_m           EX_fe2_m  0.004954           fe2_m
6            EX_fe3_m           EX_fe3_m  0.002477           fe3_m
7            EX_gsn_m           EX_gsn_m  0.133531           gsn_m
8              EX_k_m             EX_k_m  0.002477             k_m
9            EX_mg2_m           EX_mg2_m  0.002477           mg2_m
10           EX_mn2_m           EX_mn2_m  0.002477           mn2_m
11  EX_pullulan1200_m  EX_pullulan1200_m  0.006342  pullulan1200_m
12         EX_pydxn_m         EX_pydxn_m  0.002477         pydxn_m
13           EX_zn2_m           EX_zn2_m  0.002477           zn2_m
14          EX_cgly_m          EX_cgly_m  0.068348          cgly_m
15        EX_metala_m        EX_metala_m  0.104717        metala_m
16         EX_pheme_m         EX_pheme_m  0.002477         pheme_m
17            EX_q8_m            EX_q8_m  0.002477            q8_m
18           EX_nmn_m           EX_nmn_m  0.364896           nmn_m
19         EX_man6p_m         EX_man6p_m  0.364896         man6p_m
20          EX_hspg_m          EX_hspg_m  1.238542          hspg_m

In [8]:
from micom.data import test_medium
from micom.qiime_formats import load_qiime_medium

test_med = load_qiime_medium(test_medium)
test_med

                reaction       flux metabolite
reaction
EX_glc__D_m  EX_glc__D_m  10.000000   glc__D_m
EX_nh4_m        EX_nh4_m   4.362240      nh4_m
EX_o2_m          EX_o2_m  18.579253       o2_m
EX_pi_m          EX_pi_m   2.942960       pi_m

In [ ]:
from micom.workflows import grow

res = grow(manifest, model_folder="../data/micom", medium=min_med, tradeoff=1.0, threads=2)

Output()

Set parameter Username
Academic license - for non-commercial use only - expires 2024-03-01
Set parameter Username
Academic license - for non-commercial use only - expires 2024-03-01
Read LP format model from file /var/folders/1q/4qg3t0gx0sn39bk35trp5hmm0000gn/T/tmp4h64avk7.lp
Reading time = 0.11 seconds
: 13960 rows, 31643 columns, 117913 nonzeros
Read LP format model from file /var/folders/1q/4qg3t0gx0sn39bk35trp5hmm0000gn/T/tmp1oiwfltf.lp
Reading time = 0.11 seconds
: 13960 rows, 31643 columns, 117913 nonzeros

Set parameter Username
Academic license - for non-commercial use only - expires 2024-03-01
Set parameter Username
Academic license - for non-commercial use only - expires 2024-03-01
Read LP format model from file /var/folders/1q/4qg3t0gx0sn39bk35trp5hmm0000gn/T/tmphu_qhjjb.lp
Reading time = 0.11 seconds
: 13960 rows, 31643 columns, 117913 nonzeros
Read LP format model from file /var/folders/1q/4qg3t0gx0sn39bk35trp5hmm0000gn/T/tmpjxr30sls.lp
Reading time = 0.11 seconds
: 13960 rows, 31643 columns, 117913 nonzeros
Set parameter Username
Academic license - for non-commercial use only - expires 2024-03-01
Set parameter Username
Academic license - for non-commercial use only - expires 2024-03-01
Read LP format model from file /var/folders/1q/4qg3t0gx0sn39bk35trp5hmm0000gn/T/tmp7m3vxk8j.lp
Reading time = 0.11 seconds
: 13960 rows, 31643 columns, 117913 nonzeros
Read LP format model from file /var/folders/1q/4qg3t0gx0sn39bk35trp5hmm0000gn/T/tmpnhm01vfw.lp
Reading time = 0.11 seconds
: 13960 rows, 31643 columns, 117913 nonzeros

In [ ]:
from micom.workflows import tradeoff

tradeoff_rates = tradeoff(manifest, model_folder="../data/micom", medium=min_med, threads=2)
tradeoff_rates.groupby("tradeoff").apply(
    lambda df: (df.growth_rate > 1e-6).sum()).reset_index()

In [ ]:
from micom.viz import plot_tradeoff

pl = plot_tradeoff(tradeoff_rates, filename="../data/micom/micomtradeoff.html")

In [15]:
from micom.viz import plot_growth

pl = plot_growth(res, filename="../data/micom/micomgrowth_rates.html")

In [16]:
pl.view()